[dev]
   command = "pnpm run dev || ( npx pnpm install -r --store=node_modules/.pnpm-store && pnpm run dev )"

[build.environment]
  NPM_FLAGS = "--version"

[build]
  command = "pnpm run generate || ( npx pnpm install -r --store=node_modules/.pnpm-store && pnpm run generate )"
  publish = "dist"
