[dev]
   command = "pnpm run dev || ( npx pnpm install -r --store=node_modules/.pnpm-store && pnpm install && pnpm run dev )"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[build]
  command = "pnpm run generate || ( npx pnpm install -r --store=node_modules/.pnpm-store && pnpm install && pnpm run generate )"
  publish = "dist"
