[dev]
   command = "pnpm run dev || ( npm install -g pnpm && pnpm run dev )"

[build]
  command = "pnpm run generate || ( npm install -g pnpm && pnpm install && pnpm run generate )"
  publish = "dist"
